"""added

Revision ID: 060cd16f08a8
Revises: 52a39cda58b3
Create Date: 2022-08-17 22:24:53.410000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060cd16f08a8'
down_revision = '52a39cda58b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
