"""empty message

Revision ID: 40fee68c607a
Revises: eac5df9ae8d8
Create Date: 2023-02-19 21:10:57.906114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fee68c607a'
down_revision = 'eac5df9ae8d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.Column('idea', sa.VARCHAR(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_table('ideas')
    # ### end Alembic commands ###
