"""changed language_code and product description

Revision ID: 5839af201447
Revises: f7bcabedef63
Create Date: 2022-08-26 23:11:12.782000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5839af201447'
down_revision = 'f7bcabedef63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
