"""empty message

Revision ID: 616763e2d0b7
Revises: 40fee68c607a
Create Date: 2023-02-21 18:41:04.017125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616763e2d0b7'
down_revision = '40fee68c607a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('rate', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'rate')
    # ### end Alembic commands ###
