"""initial migration

Revision ID: 84e65ccd68e0
Revises: 
Create Date: 2022-08-15 01:55:22.933000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84e65ccd68e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_settings')
    op.drop_table('command_menus')
    op.drop_table('commands')
    op.drop_table('user_transactions')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('referrer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.telegram_id'], name='FK__users_referrer_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('telegram_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_transactions',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=19, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='FK__transactions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_transactions_pkey')
    )
    op.create_table('commands',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('commands_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('command_text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='commands_pkey'),
    sa.UniqueConstraint('command_text', name='commands_command_text_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('command_menus',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('in_menu', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], name='command_menus_command_id_fkey'),
    sa.PrimaryKeyConstraint('command_id', name='command_menus_pkey')
    )
    op.create_table('command_settings',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('restricted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], name='command_settings_command_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='command_settings_user_id_fkey'),
    sa.PrimaryKeyConstraint('command_id', 'user_id', name='command_settings_pkey')
    )
    # ### end Alembic commands ###
