"""empty message

Revision ID: a54d8ebad6be
Revises: 3ee7b1af2f37
Create Date: 2023-01-11 18:53:25.633620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54d8ebad6be'
down_revision = '3ee7b1af2f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
