"""empty message

Revision ID: eac5df9ae8d8
Revises: a54d8ebad6be
Create Date: 2023-01-11 18:53:52.114932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac5df9ae8d8'
down_revision = 'a54d8ebad6be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
